// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg22WY5YCwzPwxFQ1yB4t6-ENRYNbP3gY',
    appId: '1:383763145288:web:733f7dc9f931efa5e82e7d',
    messagingSenderId: '383763145288',
    projectId: 'farmfusion-exchange',
    authDomain: 'farmfusion-exchange.firebaseapp.com',
    storageBucket: 'farmfusion-exchange.appspot.com',
    measurementId: 'G-0EP438W7FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY46PTsbKQJUw2pwJEUTyVbjJCovFsiOw',
    appId: '1:383763145288:android:85ba2ba1e86fae5ee82e7d',
    messagingSenderId: '383763145288',
    projectId: 'farmfusion-exchange',
    storageBucket: 'farmfusion-exchange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOJbjmcNGVC8p15yvZuQwAUgbejA0cAg',
    appId: '1:383763145288:ios:095ee294ad04e109e82e7d',
    messagingSenderId: '383763145288',
    projectId: 'farmfusion-exchange',
    storageBucket: 'farmfusion-exchange.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEOJbjmcNGVC8p15yvZuQwAUgbejA0cAg',
    appId: '1:383763145288:ios:fdaa35074b8263b7e82e7d',
    messagingSenderId: '383763145288',
    projectId: 'farmfusion-exchange',
    storageBucket: 'farmfusion-exchange.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
